# coding: utf-8

"""
    Sample contact

    This is a sample server Contactstore server.  multiline description   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest


class TestContact(unittest.TestCase):
    """Contact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContact(self):
        """Test Contact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.contact.Contact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
