# coding: utf-8

"""
    Sample contact

    This is a sample server Contactstore server.  multiline description   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import swagger_client
import unittest


class TestContactApi(unittest.TestCase):
    """ContactApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.contact_api.ContactApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_contact(self):
        """Test case for add_contact

        Add a new contact  # noqa: E501
        """
        pass

    def test_delete_contact(self):
        """Test case for delete_contact

        Deletes a contact  # noqa: E501
        """
        pass

    def test_get_contact_by_id(self):
        """Test case for get_contact_by_id

        Find contact by ID  # noqa: E501
        """
        pass

    def test_get_contacts(self):
        """Test case for get_contacts

        list of all contact  # noqa: E501
        """
        pass

    def test_update_contact(self):
        """Test case for update_contact

        Updates a contact in the store with form data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
